import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { UserProvider } from "@auth0/nextjs-auth0/client";
import { ThemeProvider } from "@/app/context/ThemeProvider";
import { SocketProvider } from "@/app/context/SocketContext";
import { MediaStreamProvider } from "@/app/context/MediaStream";
import { MediaScreenStreamProvider } from "@/app/context/ScreenStream";
import { Toaster } from "@/components/ui/toaster";

import "./globals.css";
import { AudioVideoStreamProvider } from "./context/AudioVideoStream";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <SocketProvider>
        <UserProvider>
          <AudioVideoStreamProvider>
            <MediaStreamProvider>
              <MediaScreenStreamProvider>
                <body className={inter.className}>
                  <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                  >
                    {children}
                    <Toaster />
                  </ThemeProvider>
                </body>
              </MediaScreenStreamProvider>
            </MediaStreamProvider>
          </AudioVideoStreamProvider>
        </UserProvider>
      </SocketProvider>
    </html>
  );
}
