name: Playwright Tests
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: "yarn"
      - run: yarn install
      - run: npx playwright install chromium
      - name: Create .env file
        run: |
          echo "AUTH_SECRET=secrec777" >> apps/web/.env
          echo "NEXTAUTH_URL=https://meetn-chat.vercel.app" >> apps/web/.env
          echo "DATABASE_URL=DATABASE_URL" >> apps/web/.env
      - name: Print .env file
        run: cat apps/web/.env
      - name: Run Playwright tests
        run: yarn run ci